/**
 * Regenerates schema-v1.sql: a database exactly as Jupiter's first schema
 * version left it, with representative data. The committed fixture is the
 * frozen "previous schema" that migration tests upgrade.
 *
 *   npx tsx packages/database/test/fixtures/generate-schema-v1.ts
 *
 * Only regenerate it if migration 0001 itself is being replaced before release.
 */
import { writeFileSync } from 'node:fs'
import { DatabaseSync } from 'node:sqlite'
import { MIGRATIONS_TABLE_SQL, migrationChecksum } from '../../src/migrations'
import { JUPITER_MIGRATIONS } from '../../src/schema'

const first = JUPITER_MIGRATIONS[0]
if (!first) throw new Error('No migrations')

const actor = JSON.stringify({ type: 'user-interface', id: 'window:1' })
const core = JSON.stringify({ type: 'core', id: 'core' })
const statements = [
  '-- Jupiter database at schema version 1 (0001_settings_and_events), with sample data.',
  '-- Generated by generate-schema-v1.ts. Do not edit by hand.',
  MIGRATIONS_TABLE_SQL.trim(),
  first.sql.trim(),
  `INSERT INTO schema_migrations (version, name, checksum, applied_at) VALUES (1, '${first.name}', '${migrationChecksum(first)}', '2026-09-01T08:00:00.000Z');`,
  `INSERT INTO settings (key, value_json, updated_at, updated_by) VALUES ('logging.level', '"warn"', '2026-09-01T08:05:00.000Z', '${actor}');`,
  `INSERT INTO event_streams (stream_kind, stream_id, last_sequence, created_at) VALUES ('system', 'core', 2, '2026-09-01T08:00:00.000Z');`,
  `INSERT INTO event_streams (stream_kind, stream_id, last_sequence, created_at) VALUES ('settings', 'logging.level', 1, '2026-09-01T08:05:00.000Z');`,
  `INSERT INTO events (event_id, schema_version, type, stream_kind, stream_id, stream_sequence, occurred_at, recorded_at, correlation_id, causation_id, actor_json, mission_id, execution_id, payload_json) VALUES ('01990500-0000-7000-8000-000000000001', 1, 'core.started', 'system', 'core', 1, '2026-09-01T08:00:00.000Z', '2026-09-01T08:00:00.000Z', '01990500-0000-7000-8000-0000000000a1', NULL, '${core}', NULL, NULL, '{"coreVersion":"0.1.0-alpha.0","schemaVersion":1,"pid":4242,"restarts":0}');`,
  `INSERT INTO events (event_id, schema_version, type, stream_kind, stream_id, stream_sequence, occurred_at, recorded_at, correlation_id, causation_id, actor_json, mission_id, execution_id, payload_json) VALUES ('01990500-0000-7000-8000-000000000002', 1, 'settings.changed', 'settings', 'logging.level', 1, '2026-09-01T08:05:00.000Z', '2026-09-01T08:05:00.000Z', '01990500-0000-7000-8000-0000000000a2', NULL, '${actor}', NULL, NULL, '{"key":"logging.level","previousValue":null,"value":"warn"}');`,
  `INSERT INTO events (event_id, schema_version, type, stream_kind, stream_id, stream_sequence, occurred_at, recorded_at, correlation_id, causation_id, actor_json, mission_id, execution_id, payload_json) VALUES ('01990500-0000-7000-8000-000000000003', 1, 'core.stopped', 'system', 'core', 2, '2026-09-01T09:00:00.000Z', '2026-09-01T09:00:00.000Z', '01990500-0000-7000-8000-0000000000a3', NULL, '${core}', NULL, NULL, '{"reason":"shutdown"}');`
]

// Prove the fixture is valid SQL for SQLite before writing it.
const probe = new DatabaseSync(':memory:')
probe.exec('PRAGMA foreign_keys = ON')
probe.exec(statements.join('\n'))
probe.close()

writeFileSync(new URL('./schema-v1.sql', import.meta.url), `${statements.join('\n\n')}\n`)
console.log('schema-v1.sql written')
