-- Jupiter database at schema version 1 (0001_settings_and_events), with sample data.

-- Generated by generate-schema-v1.ts. Do not edit by hand.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version     INTEGER PRIMARY KEY NOT NULL CHECK (version >= 1),
    name        TEXT NOT NULL,
    checksum    TEXT NOT NULL CHECK (length(checksum) = 64),
    applied_at  TEXT NOT NULL
  ) STRICT;

CREATE TABLE settings (
        key         TEXT PRIMARY KEY NOT NULL CHECK (length(key) BETWEEN 1 AND 64),
        value_json  TEXT NOT NULL CHECK (json_valid(value_json)),
        updated_at  TEXT NOT NULL,
        updated_by  TEXT NOT NULL CHECK (json_valid(updated_by))
      ) STRICT;

      CREATE TABLE event_streams (
        stream_kind    TEXT NOT NULL,
        stream_id      TEXT NOT NULL,
        last_sequence  INTEGER NOT NULL CHECK (last_sequence >= 1),
        created_at     TEXT NOT NULL,
        PRIMARY KEY (stream_kind, stream_id)
      ) STRICT, WITHOUT ROWID;

      CREATE TABLE events (
        global_sequence  INTEGER PRIMARY KEY AUTOINCREMENT,
        event_id         TEXT NOT NULL UNIQUE,
        schema_version   INTEGER NOT NULL,
        type             TEXT NOT NULL,
        stream_kind      TEXT NOT NULL,
        stream_id        TEXT NOT NULL,
        stream_sequence  INTEGER NOT NULL CHECK (stream_sequence >= 1),
        occurred_at      TEXT NOT NULL,
        recorded_at      TEXT NOT NULL,
        correlation_id   TEXT NOT NULL,
        causation_id     TEXT,
        actor_json       TEXT NOT NULL CHECK (json_valid(actor_json)),
        mission_id       TEXT,
        execution_id     TEXT,
        payload_json     TEXT NOT NULL CHECK (json_valid(payload_json)),
        UNIQUE (stream_kind, stream_id, stream_sequence),
        FOREIGN KEY (stream_kind, stream_id) REFERENCES event_streams (stream_kind, stream_id) ON DELETE RESTRICT
      ) STRICT;

      CREATE INDEX events_by_type ON events (type, global_sequence);
      CREATE INDEX events_by_mission ON events (mission_id, global_sequence) WHERE mission_id IS NOT NULL;

      CREATE TRIGGER events_no_update BEFORE UPDATE ON events
        BEGIN SELECT RAISE(ABORT, 'events are append-only'); END;
      CREATE TRIGGER events_no_delete BEFORE DELETE ON events
        BEGIN SELECT RAISE(ABORT, 'events are append-only'); END;

INSERT INTO schema_migrations (version, name, checksum, applied_at) VALUES (1, '0001_settings_and_events', 'b6272b195cefd046ee3de8f47f0f160d3008d5e4e13a8e81a9a6e215dc21fb5d', '2026-09-01T08:00:00.000Z');

INSERT INTO settings (key, value_json, updated_at, updated_by) VALUES ('logging.level', '"warn"', '2026-09-01T08:05:00.000Z', '{"type":"user-interface","id":"window:1"}');

INSERT INTO event_streams (stream_kind, stream_id, last_sequence, created_at) VALUES ('system', 'core', 2, '2026-09-01T08:00:00.000Z');

INSERT INTO event_streams (stream_kind, stream_id, last_sequence, created_at) VALUES ('settings', 'logging.level', 1, '2026-09-01T08:05:00.000Z');

INSERT INTO events (event_id, schema_version, type, stream_kind, stream_id, stream_sequence, occurred_at, recorded_at, correlation_id, causation_id, actor_json, mission_id, execution_id, payload_json) VALUES ('01990500-0000-7000-8000-000000000001', 1, 'core.started', 'system', 'core', 1, '2026-09-01T08:00:00.000Z', '2026-09-01T08:00:00.000Z', '01990500-0000-7000-8000-0000000000a1', NULL, '{"type":"core","id":"core"}', NULL, NULL, '{"coreVersion":"0.1.0-alpha.0","schemaVersion":1,"pid":4242,"restarts":0}');

INSERT INTO events (event_id, schema_version, type, stream_kind, stream_id, stream_sequence, occurred_at, recorded_at, correlation_id, causation_id, actor_json, mission_id, execution_id, payload_json) VALUES ('01990500-0000-7000-8000-000000000002', 1, 'settings.changed', 'settings', 'logging.level', 1, '2026-09-01T08:05:00.000Z', '2026-09-01T08:05:00.000Z', '01990500-0000-7000-8000-0000000000a2', NULL, '{"type":"user-interface","id":"window:1"}', NULL, NULL, '{"key":"logging.level","previousValue":null,"value":"warn"}');

INSERT INTO events (event_id, schema_version, type, stream_kind, stream_id, stream_sequence, occurred_at, recorded_at, correlation_id, causation_id, actor_json, mission_id, execution_id, payload_json) VALUES ('01990500-0000-7000-8000-000000000003', 1, 'core.stopped', 'system', 'core', 2, '2026-09-01T09:00:00.000Z', '2026-09-01T09:00:00.000Z', '01990500-0000-7000-8000-0000000000a3', NULL, '{"type":"core","id":"core"}', NULL, NULL, '{"reason":"shutdown"}');
